{{ include "gateway-api-inference-extension.validations.inferencepool.common" $ }}
apiVersion: {{ .Values.inferencePool.apiVersion }}
kind: InferencePool
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gateway-api-inference-extension.labels" . | nindent 4 }}
spec:
  {{ if eq .Values.inferencePool.apiVersion "inference.networking.x-k8s.io/v1alpha2"}}
  targetPortNumber:
    {{- range .Values.inferencePool.targetPorts }}
      - number: {{ .number }}
    {{- end }}
  {{ else }}
  targetPorts:
    {{- range .Values.inferencePool.targetPorts }}
      - number: {{ .number }}
    {{- end }}
  {{- end}}
  selector:
    matchLabels:
      {{- if .Values.inferencePool.modelServers.matchLabels }}
      {{- range $key, $value := .Values.inferencePool.modelServers.matchLabels }}
      {{ $key }}: {{ quote $value }}
      {{- end }}
      {{- end }}
  endpointPickerRef:
    name: {{ include "gateway-api-inference-extension.name" . }}
    port:
      number: {{ .Values.inferenceExtension.extProcPort | default 9002 }}


