apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen-server
  template:
    metadata:
      labels:
        app: qwen-server
        ai.gke.io/model: Qwen3_32B
        ai.gke.io/inference-server: vllm
        examples.ai.gke.io/source: model-garden
    spec:
      shareProcessNamespace: true
      containers:
      - name: inference-server
        image: vllm/vllm-openai:v0.6.3.post1
        resources:
          requests:
            cpu: 5
            memory: 20Gi
            ephemeral-storage: 40Gi
            nvidia.com/gpu : 1
          limits:
            cpu: 5
            memory: 20Gi
            ephemeral-storage: 40Gi
            nvidia.com/gpu : 1
        command: ["/bin/sh", "-c"]
        args:
        - vllm serve Qwen/Qwen3-32B
        - --host=0.0.0.0
        - --port=8000
        - --tensor-parallel-size=1
        - --swap-space=16
        - --gpu-memory-utilization=0.95
        - --max-model-len=2048
        - --max-num-batched-tokens=4096
        - --disable-log-stats
        - --enable-loras
        - --max-loras=5
        env:
        - name: DEPLOY_SOURCE
          value: UI_NATIVE_MODEL
        - name: MODEL_ID
          value: "Qwen3-32B"
        - name: AIP_STORAGE_URI
          value: "gs://vertex-model-garden-public-us/qwen/qwen3-32b-hf"
        - name: VLLM_ALLOW_RUNTIME_LORA_UPDATING
          value: "true"
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token  # The name of your Kubernetes Secret
              key: token   # The specific key within the Secret
        - name: DYNAMIC_LORA_ROLLOUT_CONFIG
          value: "/config/configmap.yaml"
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      initContainers:
        - name: lora-adapter-syncer
          tty: true
          stdin: true 
          image: us-central1-docker.pkg.dev/k8s-staging-images/gateway-api-inference-extension/lora-syncer:main
          restartPolicy: Always
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: metrics
          env:
            - name: DYNAMIC_LORA_ROLLOUT_CONFIG
              value: "/config/configmap.yaml"
          volumeMounts: # DO NOT USE subPath
          - name: config-volume
            mountPath:  /config
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: config-volume
        configMap:
          name: dynamic-lora-config

---
apiVersion: v1
kind: Service
metadata:
  name: qwen-service
spec:
  selector:
    app: qwen-server
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: dynamic-lora-config
data:
  configmap.yaml: |
      vLLMLoRAConfig:
        name: uncensored-loras-qwen
        defaultBaseModel: Qwen/Qwen3-32B
        ensureExist:
          models:
          - id: uncensored-lora-v1
            source: nicoboss/Qwen3-32B-Uncensored
          - id: uncensored-lora-v3
            source: nicoboss/Qwen3-32B-Uncensored
          - id: uncensored-lora-v4
            source: nicoboss/Qwen3-32B-Uncensored
        ensureNotExist:
          models:
          - id: uncensored-lora-v2
            source: nicoboss/Qwen3-32B-Uncensored