version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - dupword
    - durationcheck
    - errcheck
    - fatcontext
    - ginkgolinter
    - goconst
    - gocritic
    - govet
    - ineffassign
    - loggercheck
    - makezero
    - misspell
    - nakedret
    - perfsprint
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    revive:
      rules:
        - name: comment-spacings
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - bin
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - bin
      - third_party$
      - builtin$
      - examples$
