site_name: Kubernetes Gateway API Inference Extension
repo_url: https://github.com/kubernetes-sigs/gateway-api-inference-extension
repo_name: kubernetes-sigs/gateway-api-inference-extension
site_dir: site
docs_dir: site-src
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  logo: images/logo/logo-text-large-horizontal-white.png
  favicon: images/favicon-64.png
  features:
    - content.code.annotate
    - content.code.copy
    - search.highlight
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - content.tabs.link
  palette:
    primary: custom
  custom_dir: site-src/overrides
edit_uri: edit/main/site-src/
plugins:
  - search
  - awesome-pages
  - macros:
      j2_line_comment_prefix: "#$"
  - mermaid2
markdown_extensions:
  - admonition
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - toc:
      permalink: true
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Overview:
    - Introduction: index.md
    - Concepts:
        API Overview: concepts/api-overview.md
        Conformance: concepts/conformance.md
        Roles and Personas: concepts/roles-and-personas.md
    - Implementations:
      - Gateways: implementations/gateways.md
    - FAQ: faq.md
  - Guides:
    - Implementer Guides:
      - Getting started: guides/implementers.md
      - Conformance Tests: guides/conformance-tests.md
  - Reference:
    - v1 API Reference: reference/spec.md
    - v1alpha1 API Reference:
      - reference/x-v1a1-spec.md
    - API Types:
      - InferencePool: api-types/inferencepool.md
      - InferencePoolImport: api-types/inferencepoolimport.md
  - Enhancements:
    - Overview: enhancements/overview.md
  - Contributing:
    - How to Get Involved: contributing/index.md
