apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: epp-insecure-tls
spec:
  host: vllm-llama3-8b-instruct-epp
  trafficPolicy:
      tls:
        mode: SIMPLE
        insecureSkipVerify: true
