apiVersion: apps/v1
kind: Deployment
metadata:
  name: instance-gateway-ext-proc
  namespace: default
  labels:
    app: instance-gateway-ext-proc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instance-gateway-ext-proc
  template:
    metadata:
      labels:
        app: instance-gateway-ext-proc
    spec:
      containers:
      - name: instance-gateway-ext-proc
        # TODO(https://github.com/kubernetes-sigs/llm-instance-gateway/issues/34) Update the image and args.
        image: <BUILT-IMAGE>
        args:
        # TODO(https://github.com/kubernetes-sigs/llm-instance-gateway/issues/12) Remove this once ext proc can dynamically reconcile on LLMServerPool.
        - -pods
        - "vllm-78665f78c4-h4kx4,vllm-78665f78c4-hnz84"
        - -podIPs
        - "10.24.11.6:8000,10.24.5.7:8000"
        ports:
        - containerPort: 9002
      - name: curl
        image: curlimages/curl
        command: ["sleep", "3600"]
---
apiVersion: v1
kind: Service
metadata:
  name: instance-gateway-ext-proc
  namespace: default
spec:
  selector:
    app: instance-gateway-ext-proc
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
  type: ClusterIP
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: ext-proc-policy
  namespace: default
spec:
  extProc:
    - backendRefs:
      - group: ""
        kind: Service
        name: instance-gateway-ext-proc
        port: 9002
      processingMode:
        request:
          body: Buffered
        response:
      # The timeouts are likely not needed here. We can experiment with removing/tuning them slowly.
      # The connection limits are more important and will cause the opaque: ext_proc_gRPC_error_14 error in Envoy GW if not configured correctly. 
      messageTimeout: 1000s
      backendSettings:
        circuitBreaker:
          maxConnections: 40000
          maxPendingRequests: 40000
          maxParallelRequests: 40000 
        timeout:
          tcp:
            connectTimeout: 24h
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: llm-route