apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "0"
spec:
  serviceName: placeholder
  replicas: 1
  selector:
    matchLabels:
      app: placeholder
  template:
    metadata:
      labels:
        app: placeholder
    spec:
      serviceAccountName: operator-controller-manager
      containers:
        - name: cmd
          image: us.icr.io/ibm-hc4ai-operator/placeholder:placeholder
          imagePullPolicy: Always
