/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	apixv1alpha2 "sigs.k8s.io/gateway-api-inference-extension/apix/v1alpha2"
)

// PoolSelectorApplyConfiguration represents a declarative configuration of the PoolSelector type for use
// with apply.
type PoolSelectorApplyConfiguration struct {
	Group            *apixv1alpha2.Group                               `json:"group,omitempty"`
	Kind             *apixv1alpha2.Kind                                `json:"kind,omitempty"`
	MatchLabels      map[apixv1alpha2.LabelKey]apixv1alpha2.LabelValue `json:"matchLabels,omitempty"`
	MatchExpressions []LabelSelectorRequirementApplyConfiguration      `json:"matchExpressions,omitempty"`
}

// PoolSelectorApplyConfiguration constructs a declarative configuration of the PoolSelector type for use with
// apply.
func PoolSelector() *PoolSelectorApplyConfiguration {
	return &PoolSelectorApplyConfiguration{}
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *PoolSelectorApplyConfiguration) WithGroup(value apixv1alpha2.Group) *PoolSelectorApplyConfiguration {
	b.Group = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *PoolSelectorApplyConfiguration) WithKind(value apixv1alpha2.Kind) *PoolSelectorApplyConfiguration {
	b.Kind = &value
	return b
}

// WithMatchLabels puts the entries into the MatchLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the MatchLabels field,
// overwriting an existing map entries in MatchLabels field with the same key.
func (b *PoolSelectorApplyConfiguration) WithMatchLabels(entries map[apixv1alpha2.LabelKey]apixv1alpha2.LabelValue) *PoolSelectorApplyConfiguration {
	if b.MatchLabels == nil && len(entries) > 0 {
		b.MatchLabels = make(map[apixv1alpha2.LabelKey]apixv1alpha2.LabelValue, len(entries))
	}
	for k, v := range entries {
		b.MatchLabels[k] = v
	}
	return b
}

// WithMatchExpressions adds the given value to the MatchExpressions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the MatchExpressions field.
func (b *PoolSelectorApplyConfiguration) WithMatchExpressions(values ...*LabelSelectorRequirementApplyConfiguration) *PoolSelectorApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMatchExpressions")
		}
		b.MatchExpressions = append(b.MatchExpressions, *values[i])
	}
	return b
}
