bbr:
  name: body-based-router
  replicas: 1
  image:
    name: bbr
    hub: us-central1-docker.pkg.dev/k8s-staging-images/gateway-api-inference-extension
    tag: main
    pullPolicy: Always
  extProcPort: 9002
