# permissions for end users to view inferencepools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/managed-by: kustomize
  name: inferencepool-viewer-role
rules:
- apiGroups:
  - inference.networking.x-k8s.io
  resources:
  - inferencepools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - inference.networking.x-k8s.io
  resources:
  - inferencepools/status
  verbs:
  - get
