apiVersion: gateway.networking.k8s.io/v1
date: "2025-06-23T17:17:39Z"
gatewayAPIChannel: standard
gatewayAPIVersion: v1.3.0
implementation:
  contact:
  - '@bobtest'
  organization: Google
  project: GKE gateway
  url: https://github.com/kubernetes-sigs/gateway-api-inference-extension
  version: v1.2.3
kind: ConformanceReport
mode: default
profiles:
- core:
    failedTests:
    - GatewayFollowingEPPRouting
    - InferencePoolHTTPRoutePortValidation
    - InferencePoolInvalidEPPService
    result: failure
    statistics:
      Failed: 3
      Passed: 4
      Skipped: 0
  name: Gateway
  summary: Core tests failed with 3 test failures.
