apiVersion: v1
kind: Service
metadata:
  name: epp-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: epp-deployment
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
  type: ClusterIP
