# Base Kubernetes resources for the Gateway API Inference Extension conformance tests.
# This includes namespaces and a minimal set of resources (Gateway, Backend)
# required by many tests. More specific resources should be defined within
# individual test files or other resource directories (e.g., sample_backends).

---
# Namespace for core infrastructure like Gateways.
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-conformance-infra
  labels:
    gateway-conformance: infra
---
# Namespace for application backends (potentially simulating model servers
# or where InferencePools might reside in some tests).
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-conformance-app-backend
  labels:
    gateway-conformance: backend
---
# A basic Gateway resource that allows HTTPRoutes from the same namespace.
# Tests can use this as a parent reference for routes that target InferencePools.
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: conformance-gateway
  namespace: gateway-conformance-infra
spec:
  # The conformance suite runner will replace this placeholder
  # with the actual GatewayClass name provided via flags.
  gatewayClassName: "{GATEWAY_CLASS_NAME}"
  listeners:
  - name: http # Standard listener name
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
      kinds:
      # Allows HTTPRoutes to attach, which can then reference InferencePools.
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
---
# --- Conformance Secondary Gateway Definition ---
# A second generic Gateway resource for tests requiring multiple Gateways.
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: conformance-secondary-gateway
  namespace: gateway-conformance-infra
spec:
  gatewayClassName: "{GATEWAY_CLASS_NAME}"
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    hostname: "secondary.example.com" # Distinct hostname to differentiate from conformance-gateway
    allowedRoutes:
      namespaces:
        from: All

### The following defines the essential resources for the gateway conformance test.
### All resources are created in the 'gateway-conformance-app-backend' namespace.
---
# Deploys a mock backend service to act as a model server.
#
# For conformance testing, a simple echo server is sufficient. The goal is to
# verify that requests are successfully routed to a backend, not to validate
# the content of the server's response. In a real-world use case, this would
# be replaced by the actual model-serving application.
#
# The Pods created by this Deployment are selected by the InferencePool resource.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend-primary-model-server-deployment
  namespace: gateway-conformance-app-backend
  labels:
    app: app-backend-primary-model-server
spec:
  selector:
    matchLabels:
      app: app-backend-primary-model-server
  template:
    metadata:
      labels:
        app: app-backend-primary-model-server
    spec:
      containers:
      - name: echoserver
        image: gcr.io/k8s-staging-gateway-api/echo-basic:v20240412-v1.0.0-394-g40c666fd
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 2
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
---
# --- Required Role and RoleBinding for Conformance Test for EPP ---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: inference-model-reader
  namespace: gateway-conformance-app-backend
rules:
- apiGroups: ["inference.networking.x-k8s.io"]
  resources: ["inferencemodels", "inferencepools"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: epp-to-inference-model-reader
  namespace: gateway-conformance-app-backend
subjects:
- kind: ServiceAccount
  name: default
  namespace: gateway-conformance-app-backend
roleRef:
  kind: Role
  name: inference-model-reader
  apiGroup: rbac.authorization.k8s.io
