# Base Kubernetes resources for the Gateway API Inference Extension conformance tests.
# This includes namespaces and a minimal set of resources (Gateway, Backend)
# required by many tests. More specific resources should be defined within
# individual test files or other resource directories (e.g., sample_backends).

---
# Namespace for core infrastructure like Gateways.
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-conformance-infra
  labels:
    gateway-conformance: infra
---
# Namespace for application backends (potentially simulating model servers
# or where InferencePools might reside in some tests).
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-conformance-app-backend
  labels:
    gateway-conformance: backend
---
# Namespace for simple web server backends. This is expected by
# the upstream conformance suite's Setup method.
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-conformance-web-backend
  labels:
    gateway-conformance: web-backend
---
# A basic Gateway resource that allows HTTPRoutes from the same namespace.
# Tests can use this as a parent reference for routes that target InferencePools.
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: conformance-gateway
  namespace: gateway-conformance-infra
spec:
  # The conformance suite runner will replace this placeholder
  # with the actual GatewayClass name provided via flags.
  gatewayClassName: "{GATEWAY_CLASS_NAME}"
  listeners:
  - name: http # Standard listener name
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
      kinds:
      # Allows HTTPRoutes to attach, which can then reference InferencePools.
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
---
# --- Conformance Secondary Gateway Definition ---
# A second generic Gateway resource for tests requiring multiple Gateways.
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: conformance-secondary-gateway
  namespace: gateway-conformance-infra
spec:
  gatewayClassName: "{GATEWAY_CLASS_NAME}"
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    hostname: "secondary.example.com" # Distinct hostname to differentiate from conformance-gateway
    allowedRoutes:
      namespaces:
        from: All
---
# --- Conformance EPP service Definition ---
apiVersion: v1
kind: Service
metadata:
  name: infra-backend-endpoint-picker
  namespace: gateway-conformance-app-backend
spec:
  selector:
    app: infra-backend-epp
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
      appProtocol: http2
  type: ClusterIP
---
# --- Conformance EPP Deployment ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-backend-epp
  namespace: gateway-conformance-app-backend
  labels:
    app: infra-backend-epp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-backend-epp
  template:
    metadata:
      labels:
        app: infra-backend-epp
    spec:
      # Conservatively, this timeout should mirror the longest grace period of the pods within the pool
      terminationGracePeriodSeconds: 130
      containers:
      - name: epp
        image: us-central1-docker.pkg.dev/k8s-staging-images/gateway-api-inference-extension/epp:main
        imagePullPolicy: Always
        args:
        - -poolName
        - "multi-gateway-pool"
        - -poolNamespace
        - "gateway-conformance-app-backend"
        - -v
        - "4"
        - --zap-encoder
        - "json"
        - -grpcPort
        - "9002"
        - -grpcHealthPort
        - "9003"
        env:
        - name: USE_STREAMING
          value: "true"
        - name: ENABLE_REQ_HEADER_BASED_SCHEDULER_FOR_TESTING # Used for conformance test.
          value: "true"
        ports:
        - containerPort: 9002
        - containerPort: 9003
        - name: metrics
          containerPort: 9090
        livenessProbe:
          grpc:
            port: 9003
            service: inference-extension
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          grpc:
            port: 9003
            service: inference-extension
          initialDelaySeconds: 5
          periodSeconds: 10
---
# --- Conformance EPP Requried Role and RoleBindings ---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: inference-model-reader
  namespace: gateway-conformance-app-backend
rules:
- apiGroups: ["inference.networking.x-k8s.io"]
  resources: ["inferencemodels", "inferencepools"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: epp-to-inference-model-reader
  namespace: gateway-conformance-app-backend
subjects:
- kind: ServiceAccount
  name: default
  namespace: gateway-conformance-app-backend
roleRef:
  kind: Role
  name: inference-model-reader
  apiGroup: rbac.authorization.k8s.io
