apiVersion: inference.networking.x-k8s.io/v1alpha1
kind: InferenceModel
metadata:
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/managed-by: kustomize
  name: sample-sql-assist
spec:
  criticality: Critical
  modelName: sql-code-assist
  poolRef:
    name: vllm-llama-31-8b-sample-pool
  targetModels:
  - name: npc-bot-v1
    weight: 50
  - name: npc-bot-v2
    weight: 50
