apiVersion: gateway.networking.k8s.io/v1
date: "2025-07-04T16:56:35+02:00"
gatewayAPIChannel: standard
gatewayAPIVersion: v1.3.0
implementation:
  contact:
  - '@istio/maintainers'
  organization: istio
  project: istio
  url: https://istio.io
  version: 1.27-alpha.0551127f00634403cddd4634567e65a8ecc499a7
kind: ConformanceReport
mode: default
profiles:
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 9
      Skipped: 0
  name: Gateway
  summary: Core tests succeeded.
