GatewayAPIInferenceExtensionVersion: v0.5.1
apiVersion: gateway.networking.k8s.io/v1
date: "2025-08-06T17:50:20-07:00"
gatewayAPIChannel: experimental
gatewayAPIVersion: v1.3.0
implementation:
  contact:
  - github.com/agentgateway/agentgateway/issues/new/choose
  organization: agentgateway
  project: agentgateway
  url: http://agentgateway.dev/
  version: v0.7.2
kind: ConformanceReport
mode: default
profiles:
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 9
      Skipped: 0
  name: Gateway
  summary: Core tests succeeded.
