apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferencePool
metadata:
  name: {{ .Values.inferencePool.name }}
spec:
  targetPortNumber: 8000
  selector:
      {{- range $key, $value := .Values.inferencePool.selector }}
      {{ $key }}: {{ quote $value }}
      {{- end }}
  extensionRef:
    name: {{ include "gateway-api-inference-extension.name" . }}