---
# Source: InferencePool/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pool-1-epp
  namespace: default
  labels:
    app.kubernetes.io/name: pool-1-epp
    app.kubernetes.io/version: "0.2.0"
---
# Source: InferencePool/templates/rbac.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pool-1-epp
  labels:
    app.kubernetes.io/name: pool-1-epp
    app.kubernetes.io/version: "0.2.0"
rules:
- apiGroups: ["inference.networking.x-k8s.io"]
  resources: ["inferencemodels, inferencepools"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
# Source: InferencePool/templates/rbac.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pool-1-epp
subjects:
- kind: ServiceAccount
  name: pool-1-epp
  namespace: default
roleRef:
  kind: ClusterRole
  name: pool-1-epp
---
# Source: InferencePool/templates/inferencepool.yaml
apiVersion: v1
kind: Service
metadata:
  name: pool-1-epp
  namespace: default
  labels:
    app.kubernetes.io/name: pool-1-epp
    app.kubernetes.io/version: "0.2.0"
spec:
  selector:
    app: pool-1-epp
  ports:
    - name: grpc-ext-proc
      protocol: TCP
      port: 9002
    - name: http-metrics
      protocol: TCP
      port: 9090
  type: ClusterIP
---
# Source: InferencePool/templates/inferencepool.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pool-1-epp
  namespace: default
  labels:
    app.kubernetes.io/name: pool-1-epp
    app.kubernetes.io/version: "0.2.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pool-1-epp
  template:
    metadata:
      labels:
        app: pool-1-epp
    spec:
      serviceAccountName: pool-1-epp
      containers:
      - name: epp
        image: us-central1-docker.pkg.dev/k8s-staging-images/gateway-api-inference-extension/epp:main
        imagePullPolicy: Always
        args:
        - -poolName
        - pool-1
        - -poolNamespace
        - default
        - -v
        - "3"
        - -grpcPort
        - "9002"
        - -grpcHealthPort
        - "9003"
        - -metricsPort
        - "9090"
        ports:
        - name: grpc
          containerPort: 9002
        - name: grpc-health
          containerPort: 9003
        - name: metrics
          containerPort: 9090
        livenessProbe:
          grpc:
            port: 9003
            service: inference-extension
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          grpc:
            port: 9003
            service: inference-extension
          initialDelaySeconds: 5
          periodSeconds: 10
---
# Source: InferencePool/templates/inferencepool.yaml
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferencePool
metadata:
  name: pool-1
  namespace: default
  labels:
    app.kubernetes.io/name: pool-1-epp
    app.kubernetes.io/version: "0.2.0"
spec:
  targetPortNumber: 8000
  selector:
      app: "vllm-llama2-7b"
  extensionRef:
    name: pool-1-epp
