apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceModel
metadata:
  name: tweet-summarizer
spec:
  modelName: tweet-summary
  criticality: Critical
  poolRef:
    name: vllm-llama2-7b
  targetModels:
  - name: tweet-summary-1
    weight: 100

---
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceModel
metadata:
  name: base-model
spec:
  modelName: meta-llama/Llama-2-7b-hf
  criticality: Critical
  poolRef:
    name: vllm-llama2-7b

---
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceModel
metadata:
  name: base-model-cpu
spec:
  modelName: Qwen/Qwen2.5-1.5B-Instruct
  criticality: Critical
  poolRef:
    name: vllm-llama2-7b
