apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceModel
metadata:
  name: inferencemodel-sample
spec:
  modelName: tweet-summary
  criticality: Critical
  poolRef:
    name: my-pool
  targetModels:
  - name: tweet-summary-1
    weight: 100

---
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceModel
metadata:
  name: inferencemodel-base-model
spec:
  modelName: meta-llama/Llama-2-7b-hf
  criticality: Critical
  poolRef:
    name: my-pool

---
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceModel
metadata:
  name: inferencemodel-base-model-cpu
spec:
  modelName: Qwen/Qwen2.5-1.5B-Instruct
  criticality: Critical
  poolRef:
    name: my-pool
