apiVersion: v1
kind: Service
metadata:
  labels:
    generated-by: benchmark-catalog-cli
  name: model-server-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8000
  selector:
    app: model-server-deployment
  type: LoadBalancer
